export const PLATFORM_AUDIT_ACTIONS = {
  ORG_CREATED: 'ORG_CREATED',
  ORG_FIRST_ADMIN_CREATED: 'ORG_FIRST_ADMIN_CREATED',
  ORG_STATUS_CHANGED: 'ORG_STATUS_CHANGED',
  ORG_CRM_CHANGED: 'ORG_CRM_CHANGED',
} as const;
